### PR TITLE
Initial support for building operators on PNC

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@cunningt this is not ready yet, I think ... but wanted to get an early feedback. Wdyt?

**Review by cunningt — APPROVED** [review]
This looks great, but my one suggestion would be to merge all of the golang build statements into maven so you can take advantage of PME's version alignment fully.    camel-k needs the camel-k-runtime version, so if we build within maven, we can use that version.

See https://github.com/jboss-fuse/fuse-jenkins-pipelines/blob/master/8.0/patches/camel-k.patch#L151-L264

**Comment by orpiske** [comment]
> This looks great, but my one suggestion would be to merge all of the golang build statements into maven so you can take advantage of PME's version alignment fully. camel-k needs the camel-k-runtime version, so if we build within maven, we can use that version.
> 
> See https://github.com/jboss-fuse/fuse-jenkins-pipelines/blob/master/8.0/patches/camel-k.patch#L151-L264

Thanks, I like this idea as Maven/PME would do the alignment in this case. I think this change might be too much for 7.7, though ... so I'll go back to this for 7.8.

**Comment by orpiske** [comment]
Closing. I'll reevaluate again in 7.8.

**Pull request closed without merging**
